Project sprint 7 quiz
Georgiy-N/MovieQuiz-ios pull request #5
Opened 2023-02-08 05:55 UTC by Georgiy-N

Привет!
Сделал и проверил, должно работать. Постарался порядок функций и переменных правильный сделать)

2023-02-08 20:50 UTC, ABashkirova requested changes
В процессе выполнения задач ты сделал много таргетов для тестов, давай удалим те, что не содержат кода. Удалять через минус:
<img width="1512" alt="Снимок экрана 2023-02-08 в 22 46 23" src="https://user-images.githubusercontent.com/20269264/217647872-14746352-fb0d-48b9-8693-d3f7db42a138.png">

2023-02-08 20:50 UTC, ABashkirova commented on MovieQuizTests/PresenterConvertTest.swift
> +final class MovieQuizViewControllerProtocolMock: MovieQuizViewControllerProtocol {
Обращу внимание на нейминг, суффикс Protocol обычно добавляют протоколам. В классе такое слово выглядит нелепо. А вот слово Mock в классе уместно. Поэтому стоит поправить так
```suggestion
final class MovieQuizViewControllerMock: MovieQuizViewControllerProtocol {
```

2023-02-08 20:50 UTC, ABashkirova commented on MovieQuiz/Services/MovieQuizViewControllerProtocol.swift
> +    var alertPresenter: AlertPresenter? { get set }
давай вместо того, чтобы эти свойства запихивать элементы в протокол, напишем недостающие интерфейсы общения с этими свойствами. 

То есть оставляем activityIndicator приватным во vieweControlller, но чтобы изменить его состояния дописываем функции (showLoading, hideLoading). 

Аналогично с презентером, допиши такие функции, чтобы было достаточно вызвать на презентере код, который покажет алерт.

2023-02-08 20:50 UTC, ABashkirova commented on MovieQuiz/Services/MovieQuizViewControllerProtocol.swift
> +    func presentAlert(alert: UIAlertController)
еще один индикатор правильно ли ты поделил ответственности: в архитектуре MVP нужно стремиться, чтобы UIKit-вые сущности не проникали в Presenter (в нашем проекте тут исключение у AlertPresenter). 

Нужно переписать так, чтобы передавалась модель, а не контроллер

2023-02-08 20:50 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +final class MovieQuizPresenter: QuestionFactoryDelegate {
Очень много открытых методов и свойств, которые доступны вьюконтроллеру. Надо закрыть протоколом только те, которые нужны вью контроллеру и сохранять презентер по протоколу. Это значит что нужно дописать MovieQuizPresenterProtocol. Вынести туда все, что нужно контроллеру. Подписать под протокол MovieQuizPresenter. Во вью контроллере сохранить ссылку типа MovieQuizPresenterProtocol

2023-02-08 20:50 UTC, ABashkirova commented on MovieQuizUITests/MovieQuizUITests.swift
> +    }
этот тест лишний, надо удалить

2023-02-08 21:27 UTC, mmbabaev requested changes

2023-02-08 21:46 UTC, ABashkirova commented
Мы с @mmbabaev не поделили твою работу, поэтому у тебя будет двойная проверка :)  @Georgiy-N приносим извинения, не пугайся :)

2023-02-10 21:41 UTC, mmbabaev approved these changes

2023-02-10 21:41 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        viewController?.activityIndicatorStopAnimation()
здесь вы вызываете activityIndicatorStopAnimation три раза подряд (второй раз внутри requestNextQuestion), это не нужно

2023-02-10 21:41 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        viewController?.removeImageBorder()
в целом нормально, но обычно для view, c которым взаимодействует presenter, не делают так много функций.

removeImageBorder, enableButtons -  это детали реализациии View.

 По идее Presenter должен отдать View команду сделать что-то, а дальше View сама должна знать, что на это действие нужно включить кнопки и убрать. 

Например, здесь в else я бы объединил все функции в протоколе View под какую-то одну, которая не знает о деталях отображения. `prepareForNextQuestion`

2023-02-27 05:05 UTC, merged